(function(L){
  'use strict';
  const clone=value=>JSON.parse(JSON.stringify(value));
  const getPath=(root,path)=>String(path||'').split('.').filter(Boolean).reduce((o,k)=>o?.[k],root);
  const parentPath=(root,path)=>{const keys=String(path).split('.').filter(Boolean),last=keys.pop();return {parent:keys.reduce((o,k)=>o?.[k],root),key:last}};
  const printable=value=>typeof value==='object'?JSON.stringify(value):String(value);
  class ConfigEngine{
    constructor(storage){this.storage=storage}
    exportConfig(){const s=this.storage.getState();return {$schema:'lingshi-config/v2',schemaVersion:2,profile:clone(s.profile),settings:clone(s.settings),tasks:clone(s.tasks.items.map(({done,...x})=>x)),products:clone(s.shop.items.filter(x=>!x.generated)),extensionConfig:clone(s.extensionData)}}
    parse(input){const doc=typeof input==='string'?JSON.parse(input):clone(input);if(!['lingshi-config/v2','lingshi-patch/v2'].includes(doc.$schema))throw new Error('不支持的 $schema');return doc}
    preview(input){const doc=this.parse(input),before=clone(this.storage.getState()),after=clone(before);const diffs=[];this.applyDocument(after,doc,diffs);return {doc,before,after,diffs}}
    apply(input){const result=this.preview(input);this.storage.backup('before-config-import');this.storage.replace(result.after);L.events.emit('config.applied',{schema:result.doc.$schema,diffs:result.diffs});return result}
    applyDocument(state,doc,diffs){if(doc.$schema==='lingshi-config/v2'){if(doc.profile)this.setObject(state,'profile',doc.profile,diffs);if(doc.settings)this.setObject(state,'settings',doc.settings,diffs);if(doc.tasks){diffs.push({op:'replace',target:'tasks.items',before:state.tasks.items.length+' 项',after:doc.tasks.length+' 项'});state.tasks.items=clone(doc.tasks).map(x=>({...x,done:false}))}if(doc.products){const generated=state.shop.items.filter(x=>x.generated);diffs.push({op:'replace',target:'shop.items',before:state.shop.items.filter(x=>!x.generated).length+' 项',after:doc.products.length+' 项'});state.shop.items=[...clone(doc.products),...generated]}if(doc.extensionConfig)this.setObject(state,'extensionData',doc.extensionConfig,diffs);return}if(!Array.isArray(doc.operations))throw new Error('operations 必须是数组');doc.operations.forEach((op,index)=>this.applyOperation(state,op,diffs,index))}
    setObject(state,path,value,diffs){const {parent,key}=parentPath(state,path);if(!parent)throw new Error(`找不到 ${path}`);const before=clone(parent[key]);parent[key]={...(parent[key]||{}),...clone(value)};diffs.push({op:'set',target:path,before,after:clone(parent[key])})}
    applyOperation(state,op,diffs,index){const fail=m=>{throw new Error(`第 ${index+1} 项：${m}`)};if(['enable','disable'].includes(op.op)){if(!op.extensionId)fail('缺少 extensionId');const list=state.extensions.disabled;const before=list.includes(op.extensionId);if(op.op==='disable'&&!before)list.push(op.extensionId);if(op.op==='enable'&&before)list.splice(list.indexOf(op.extensionId),1);diffs.push({op:op.op,target:`extension:${op.extensionId}`,before:before?'disabled':'enabled',after:op.op==='disable'?'disabled':'enabled'});return}if(op.op==='installExtension'){if(!op.value?.id)fail('扩展包缺少 id');state.extensions.installedData=state.extensions.installedData.filter(x=>x.id!==op.value.id);state.extensions.installedData.push(clone(op.value));diffs.push({op:'installExtension',target:op.value.id,before:'未安装',after:op.value.version||'installed'});return}if(op.op==='uninstallExtension'){const before=state.extensions.installedData.length;state.extensions.installedData=state.extensions.installedData.filter(x=>x.id!==op.extensionId);diffs.push({op:'uninstallExtension',target:op.extensionId,before:before===state.extensions.installedData.length?'未安装':'已安装',after:'未安装'});return}if(op.op==='adjustBalance'){const old=state.economy.balance;state.economy.balance=Math.max(0,old+Number(op.amount||0));state.economy.transactions.push({id:L.uid('tx'),time:new Date().toISOString(),amount:Number(op.amount||0),label:op.label||'批量调整',meta:{configPatch:true}});diffs.push({op:'adjustBalance',target:'economy.balance',before:old,after:state.economy.balance});return}
      const collection=getPath(state,op.collection);if(!Array.isArray(collection))fail(`collection ${op.collection} 不是数组`);const locate=()=>{const i=collection.findIndex(x=>x.id===op.id);if(i<0)fail(`找不到 id ${op.id}`);return i};if(op.op==='add'){if(!op.value?.id)fail('value.id 不能为空');if(collection.some(x=>x.id===op.value.id))fail(`id ${op.value.id} 已存在`);collection.push(clone(op.value));diffs.push({op:'add',target:`${op.collection}#${op.value.id}`,before:'—',after:clone(op.value)});return}if(op.op==='remove'){const i=locate(),old=collection[i];collection.splice(i,1);diffs.push({op:'remove',target:`${op.collection}#${op.id}`,before:clone(old),after:'—'});return}if(['set','multiply'].includes(op.op)){const targets=op.id?[collection[locate()]]:op.where?collection.filter(x=>x[op.where.field]===op.where.equals):collection;if(!op.field)fail('缺少 field');if(!targets.length)fail('没有匹配项目');for(const item of targets){const old=item[op.field];item[op.field]=op.op==='multiply'?Number(old)*Number(op.factor):clone(op.value);diffs.push({op:op.op,target:`${op.collection}#${item.id}.${op.field}`,before:old,after:item[op.field]})}return}fail(`未知操作 ${op.op}`)}
    formatDiff(diff){return `${diff.target}: ${printable(diff.before)} → ${printable(diff.after)}`}
  }
  L.services.config=new ConfigEngine(L.services.storage);
})(window.Lingshi);
