(function(L){
  'use strict';
  const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
  class Shell{
    constructor(){this.activePage=null;this.activeSetting=null;this.pageCleanup=null;this.settingCleanup=null}
    context(){return {L,state:L.services.storage.getState(),services:L.services,escape:L.escape,money:n=>Number(n||0).toLocaleString('zh-CN'),renderSlot:id=>this.renderSlot(id),toast:m=>this.toast(m),openModal:s=>this.openModal(s),closeModal:()=>this.closeModal(),refresh:()=>this.render()}}
    start(){this.bindChrome();const pages=L.registries.pages.list().sort((a,b)=>(a.order||0)-(b.order||0));this.activePage=pages[0]?.id;this.render();L.events.on('storage.replaced',()=>this.render(),'core.shell');L.events.on('theme.activated',()=>this.renderHeader(),'core.shell')}
    bindChrome(){$('#settings-open').onclick=()=>this.openSettings();$('#settings-close').onclick=()=>this.closeSettings();$('#scrim').onclick=()=>this.closeSettings();$('#modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')this.closeModal()};$('#quick-night').onclick=()=>{try{L.services.theme.quickNight();this.toast('昼夜之境已经切换')}catch(e){this.toast(e.message)}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){this.closeModal();this.closeSettings()}if((e.ctrlKey||e.metaKey)&&e.key===','){e.preventDefault();this.openSettings()}})}
    render(){this.renderHeader();this.renderNav();this.renderPage();if($('#settings-drawer').classList.contains('show'))this.renderSettings()}
    renderHeader(){const s=L.services.storage.getState();$$('[data-profile-name]').forEach(el=>el.textContent=s.profile.name);$('#today-date').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'});L.services.theme.apply()}
    renderNav(){const pages=L.registries.pages.list().sort((a,b)=>(a.order||0)-(b.order||0));if(!pages.some(p=>p.id===this.activePage))this.activePage=pages[0]?.id;$('#main-nav').innerHTML=pages.map(p=>`<button class="${p.id===this.activePage?'active':''}" data-page-id="${L.escape(p.id)}">${L.escape(p.label)}</button>`).join('');$$('[data-page-id]').forEach(b=>b.onclick=()=>{this.activePage=b.dataset.pageId;this.renderNav();this.renderPage()})}
    renderPage(){this.pageCleanup?.();this.pageCleanup=null;const page=L.registries.pages.get(this.activePage),root=$('#page-root');if(!page){root.innerHTML='<div class="empty">没有可用页面。</div>';return}try{root.innerHTML=page.render(this.context());this.pageCleanup=page.mount?.(root,this.context())||null;this.mountSlots(root)}catch(error){root.innerHTML=`<div class="empty">页面扩展加载失败：${L.escape(error.message)}</div>`;L.errors.push({extension:page.__owner,stage:'page.render',message:error.message,time:Date.now()})}}
    renderSlot(id){return `<div class="slot" data-slot="${L.escape(id)}"></div>`}
    mountSlots(root){root.querySelectorAll('[data-slot]').forEach(el=>{const entries=L.registries.slots.list(el.dataset.slot);for(const item of entries){try{const wrap=document.createElement('div');wrap.innerHTML=item.render(this.context());el.append(...wrap.childNodes);item.mount?.(el,this.context())}catch(error){L.errors.push({extension:item.__owner,stage:'slot:'+el.dataset.slot,message:error.message,time:Date.now()})}}})}
    openSettings(section){const list=L.registries.settingsSections.list().sort((a,b)=>(a.order||0)-(b.order||0));this.activeSetting=section||this.activeSetting||list[0]?.id;$('#settings-drawer').classList.add('show');$('#scrim').classList.add('show');$('#settings-open').classList.add('open');this.renderSettings()}
    closeSettings(){$('#settings-drawer').classList.remove('show');$('#scrim').classList.remove('show');$('#settings-open').classList.remove('open')}
    renderSettings(){this.settingCleanup?.();this.settingCleanup=null;const list=L.registries.settingsSections.list().sort((a,b)=>(a.order||0)-(b.order||0));if(!list.some(x=>x.id===this.activeSetting))this.activeSetting=list[0]?.id;$('#settings-nav').innerHTML=list.map(x=>`<button class="${x.id===this.activeSetting?'active':''}" data-setting-id="${L.escape(x.id)}">${L.escape(x.label)}</button>`).join('');$$('[data-setting-id]').forEach(b=>b.onclick=()=>{this.activeSetting=b.dataset.settingId;this.renderSettings()});const section=L.registries.settingsSections.get(this.activeSetting),root=$('#settings-content');if(!section){root.innerHTML='';return}try{root.innerHTML=section.render(this.context());this.settingCleanup=section.mount?.(root,this.context())||null}catch(error){root.innerHTML=`<div class="status-error">设置扩展失败：${L.escape(error.message)}</div>`}}
    openModal(spec){const root=$('#modal-card');root.innerHTML=spec.html;$('#modal-backdrop').classList.add('show');spec.mount?.(root,this.context())}
    closeModal(){$('#modal-backdrop').classList.remove('show');$('#modal-card').innerHTML=''}
    toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
  }
  L.Shell=Shell;
})(window.Lingshi);
