(function(L){
  'use strict';
  const TOKEN_NAMES=['--color-background-primary','--color-background-glow','--color-surface-card','--color-surface-raised','--color-surface-glass','--color-text-primary','--color-text-muted','--color-border-soft','--color-accent-primary','--color-accent-secondary','--color-luxury','--color-luxury-bright','--color-danger','--shadow-card','--shadow-luxury','--radius-card','--radius-control','--font-display','--font-body','--motion-fast','--motion-slow','--hero-image','--hero-overlay'];
  class ThemeService{
    constructor(storage){this.storage=storage;this.cleanup=null;this.installedIds=new Set();L.events.on('config.applied',()=>{this.refreshInstalled();this.apply()},'core.theme')}
    list(){return L.registries.themes.list()}
    active(){return L.registries.themes.get(this.storage.getState().themes.active)||L.registries.themes.list().find(x=>!Number(x.license?.price||0))||L.registries.themes.list()[0]}
    access(theme){if(!theme)return false;if(!Number(theme.license?.price||0))return true;const until=this.storage.getState().themes.access[theme.id];return !!until&&until>Date.now()}
    grant(themeId,durationDays){const state=this.storage.getState(),until=Date.now()+Number(durationDays||1)*86400000;state.themes.access[themeId]=Math.max(state.themes.access[themeId]||0,until);this.storage.save();L.events.emit('theme.unlocked',{themeId,until});return until}
    activate(themeId){const theme=L.registries.themes.get(themeId);if(!theme)throw new Error('主题未安装');if(!this.access(theme))throw new Error('主题尚未解锁或已经过期');const state=this.storage.getState();state.themes.active=themeId;if(theme.quickRole!=='night')state.themes.lastDay=themeId;this.storage.save();this.apply();L.events.emit('theme.activated',{theme});return theme}
    quickNight(){const state=this.storage.getState(),active=this.active(),night=this.list().find(x=>x.quickRole==='night');if(!night)throw new Error('没有安装夜间主题');const target=active?.quickRole==='night'?(L.registries.themes.get(state.themes.lastDay)||this.list().find(x=>x.quickRole==='day')):night;if(!target)throw new Error('没有可切换的主题');return this.activate(target.id)}
    apply(){let theme=this.active();if(!theme||!this.access(theme)){theme=this.list().find(x=>!Number(x.license?.price||0));this.storage.getState().themes.active=theme?.id||null}if(!theme)return;try{this.cleanup?.();this.cleanup=null;TOKEN_NAMES.forEach(k=>document.documentElement.style.removeProperty(k));for(const [key,value] of Object.entries(theme.tokens||{}))if(TOKEN_NAMES.includes(key))document.documentElement.style.setProperty(key,String(value));document.body.dataset.theme=theme.id;let style=document.getElementById('active-theme-style');if(!style){style=document.createElement('style');style.id='active-theme-style';document.head.appendChild(style)}style.textContent=theme.styles||'';const layer=document.getElementById('theme-layer');layer.innerHTML='';if(typeof theme.mount==='function')this.cleanup=theme.mount({layer,events:L.events,services:L.services,state:this.storage.getState()})||null;L.events.emit('theme.applied',{theme})}catch(error){L.errors.push({extension:theme.__owner||theme.id,stage:'theme.apply',message:error.message,time:Date.now()});document.getElementById('theme-layer').innerHTML=''}}
    play(cue){if(!this.storage.getState().settings.sounds)return;const source=this.active()?.media?.sounds?.[cue];if(!source)return;try{const audio=new Audio(source);audio.volume=.35;audio.play().catch(()=>{})}catch(error){}}
    refreshInstalled(){for(const pack of this.storage.getState().extensions.installedData||[]){if(pack.type!=='theme'||!pack.contributions?.theme||this.installedIds.has(pack.id))continue;try{const theme={...pack.contributions.theme,id:pack.id,license:pack.license||pack.contributions.theme.license||{price:0,durationDays:0}};L.registries.themes.register(pack.id,theme,pack.id);this.installedIds.add(pack.id)}catch(error){L.errors.push({extension:pack.id,stage:'data-theme.install',message:error.message,time:Date.now()})}}
  }
  }
  L.services.theme=new ThemeService(L.services.storage);
  L.events.on('currency.earned',()=>L.services.theme.play('earn'),'core.theme');
  L.events.on('shop.purchased',()=>L.services.theme.play('purchase'),'core.theme');
})(window.Lingshi);
